services:
  mongo:
    image: mongo:latest
    container_name: tomato_mongo_instance
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: CPEN321_tomato
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    command: npm start


volumes:
  mongo_data: